from __future__ import annotations

import json
import logging
import os
from pathlib import Path
from typing import TYPE_CHECKING, Any, Callable, Dict, List, Optional

from agent_gem.tools import MediaWikiTool, SearchTool, VisitTool

from ..base import BaseAgent
from .answer_generator import AnswerGeneratorMixin
from .entity_sampler import Entity, EntitySamplerMixin
from .prompt_mixin import PromptMixin
from .question_constructor import QuestionConstructorMixin
from .verification import VerifierMixin

if TYPE_CHECKING:  # pragma: no cover
    from agent_gem.generator import GenerationRequest

logger = logging.getLogger(__name__)


class SearchAgent(
    EntitySamplerMixin,
    QuestionConstructorMixin,
    AnswerGeneratorMixin,
    VerifierMixin,
    PromptMixin,
    BaseAgent,
):
    """Search agent that generates tasks and answers using search tools.

    This agent performs the following pipeline:
    1. Samples entities from specified domains
    2. Constructs multi-hop questions for each entity
    3. Generates candidate answers using multiple agent configurations
    4. Verifies answers and filters results based on verification criteria
    """

    agent_type = "search_agent"
    description = "Search agent that generates tasks and answers using search tools"

    search_tool = SearchTool(
        cache_path=Path(os.getenv("SEARCH_CACHE_PATH", "")),
        api_key=os.getenv("SERPER_API_KEY"),
    )
    visit_tool = VisitTool(api_key=os.getenv("JINA_API_KEY"))
    wiki_tool = MediaWikiTool()

    def generate(self, request: GenerationRequest) -> List[Dict[str, Any]]:
        """Generate tasks and answers using search tools.

        Args:
            request: Generation request containing domain, entity count, task count,
                    search parameters, and verification requirements.

        Returns:
            List of dictionaries containing question-answer pairs with metadata:
            - question: The generated question
            - answer: The ground-truth answer
            - entity: Entity name
            - domain: Entity domain
            - description: Entity description
            - search_context: Search results used for question construction
            - candidates: List of candidate answers generated by different agents
            - verification_results: List of verification results for each candidate
        """
        if not request.domain:
            logger.warning("No domains specified, using domains by generation")
            request.domain = self._get_domains(request.num_domains)

        logger.info(
            f"Starting generation for domains: {request.domain}, "
            f"entities per domain: {request.num_entities_each_domain}"
        )

        # Get tool call map wrapped with request constraints
        tool_call_map = self._get_tool_call_map_for_request(request)

        # Step 1: Entity Sampling
        entities = self.sample_entities(
            llm=self.llm,
            tools=self._get_tools_info(),
            tool_call_map=tool_call_map,
            num_entities_each_domain=request.num_entities_each_domain,
            domains=request.domain,
            num_iterations=request.search_depth,
            entities_per_entity=request.search_breadth,
        )
        logger.info(f"Sampled {len(entities)} entities")

        # Step 2: Question Construction
        tasks: Dict[str, List] = {}
        for entity in entities:
            logger.info(f"Constructing questions for entity: {entity.name}")
            task_list = self._construct_question(
                llm=self.llm,
                tools=self._get_tools_info(),
                tool_call_map=tool_call_map,
                entity=entity,
                num_tasks=request.num_tasks_each_entity,
            )
            tasks[entity.name] = task_list
            logger.info(f"Generated {len(task_list)} questions for {entity.name}")

        # Step 3: Answer Generation and Verification
        results: List[Dict[str, Any]] = []
        for entity_name, task_list in tasks.items():
            for qa_pair in task_list:
                logger.info(f"Generating answers for question: {qa_pair.question[:50]}...")

                candidates = self._generate_answers(
                    llm=self.llm,
                    tools=self._get_tools_info(),
                    tool_call_map=tool_call_map,
                    qa_pair=qa_pair,
                )
                logger.info(f"Generated {len(candidates)} candidate answers")

                should_retain, verification_results = self._verify_candidates(
                    llm=self.llm,
                    qa_pair=qa_pair,
                    candidates=candidates,
                    require_all_incorrect=request.require_all_incorrect,
                )

                if should_retain:
                    results.append(
                        {
                            "question": qa_pair.question,
                            "answer": qa_pair.answer,
                            "entity": qa_pair.entity.name,
                            "domain": qa_pair.entity.domain,
                            "description": qa_pair.entity.description,
                            "pageview": qa_pair.entity.pageview,
                            "parent": qa_pair.entity.parent.name if qa_pair.entity.parent else None,
                            "search_context": qa_pair.search_context,
                            "candidates": [candidate.answer for candidate in candidates],
                            "verification_results": [result.is_correct for result in verification_results],
                        }
                    )
                    logger.info(f"Retained QA pair for entity: {entity_name}")

        logger.info(f"Generated {len(results)} verified question-answer pairs")
        return results

    def _get_tools_info(self) -> List[Dict[str, Any]]:
        """Get the tools information for the agent.

        Returns:
            List of tool specifications in OpenAI function calling format.
        """
        return [
            {
                "type": "function",
                "function": {
                    "name": "search",
                    "description": "Search the web for information",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "query": {
                                "type": "string",
                                "description": "The search query",
                            },
                            "max_results": {
                                "type": "integer",
                                "description": "The maximum number of results to return",
                            },
                            "depth": {
                                "type": "integer",
                                "description": "Use depth=2, 3, 4+ to get more obscure, less common results that appear deeper in search results. When you need to find obscure facts, metadata, or technical details, try deeper depth (2-10).",
                            },
                        },
                        "required": ["query", "max_results", "depth"],
                    },
                },
            },
            {
                "type": "function",
                "function": {
                    "name": "visit",
                    "description": "Visit a website and extract relevant content",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "url": {
                                "type": "string",
                                "description": "The URL to visit",
                            },
                            "goal": {
                                "type": "string",
                                "description": "The goal of the visit",
                            },
                        },
                        "required": ["url", "goal"],
                    },
                },
            },
        ]

    def _get_tool_call_map(self) -> Dict[str, Callable]:
        """Get the tool call map for the agent.

        Returns:
            Dictionary mapping tool names to their execution functions.
        """
        return {
            "search": self.search_tool.execute,
            "visit": self.visit_tool.execute,
        }

    def _get_tool_call_map_for_request(self, request: GenerationRequest) -> Dict[str, Callable]:
        """Get the tool call map for the agent, wrapped to respect request constraints.

        Args:
            request: The generation request containing search constraints.

        Returns:
            Dictionary mapping tool names to their wrapped execution functions.
        """

        def wrapped_search(query: str, max_results: int = 5, depth: int = 1) -> List[Dict[str, str]]:
            # Clamp depth and max_results to request constraints
            clamped_depth = min(max(1, depth), request.search_depth)
            clamped_breadth = min(max(1, max_results), request.search_breadth)
            return self.search_tool.execute(query, max_results=clamped_breadth, depth=clamped_depth)

        return {
            "search": wrapped_search,
            "visit": self.visit_tool.execute,
        }

    def _get_domains(self, num_domains: int) -> List[str]:
        """Get the domains for the agent.

        Returns:
            List of domain names.
        """
        messages = [
            {
                "role": "system",
                "content": self.SYSTEM_PROMPT,
            },
            {
                "role": "user",
                "content": self.DOMAIN_SAMPLER_PROMPT.format(num_domains=1),
            },
        ]
        domains = []
        while len(domains) < num_domains:
            response = self.llm.chat_completion(messages=messages, temperature=1.0)
            domain = json.loads(response)[0]
            if domain not in domains:
                domains.append(domain)
        return domains
