from __future__ import annotations

import json
import logging
import os
import threading
import uuid
from concurrent.futures import ThreadPoolExecutor, as_completed
from os.path import exists
from pathlib import Path
from typing import TYPE_CHECKING, Any, Callable, Dict, List, Optional

import faiss
import ftfy
import torch
from sentence_transformers import SentenceTransformer

from agent_gem.tools import MediaWikiTool, SearchTool, VisitTool

from ..base import BaseAgent
from .answer_generator import AnswerGeneratorMixin
from .entity_sampler import Entity, EntitySamplerMixin
from .prompt_mixin import PromptMixin
from .question_constructor import QuestionConstructorMixin
from .verification import VerifierMixin

if TYPE_CHECKING:  # pragma: no cover
    from agent_gem.generator import GenerationRequest

logger = logging.getLogger(__name__)


class SearchAgent(
    EntitySamplerMixin,
    QuestionConstructorMixin,
    AnswerGeneratorMixin,
    VerifierMixin,
    PromptMixin,
    BaseAgent,
):
    """Search agent that generates tasks and answers using search tools.

    This agent performs the following pipeline:
    1. Samples entities from specified domains
    2. Constructs multi-hop questions for each entity
    3. Generates candidate answers using multiple agent configurations
    4. Verifies answers and filters results based on verification criteria
    """

    agent_type = "search_agent"
    description = "Search agent that generates tasks and answers using search tools"

    search_tool = SearchTool(
        cache_path=Path(os.getenv("SEARCH_CACHE_PATH", "search_cache.json")),
        api_key=os.getenv("SERPER_API_KEY"),
    )
    visit_tool = VisitTool(api_key=os.getenv("JINA_API_KEY"))
    wiki_tool = MediaWikiTool()

    embedding: SentenceTransformer = None
    faiss_index: faiss.Index = None
    text_mapping: Dict = {}
    _file_lock: threading.Lock = None
    _index_lock: threading.Lock = None

    def generate(
        self, request: GenerationRequest, output_file: Optional[str] = None
    ) -> List[Dict[str, Any]]:
        """Generate tasks and answers using search tools.

        Args:
            request: Generation request containing domain, entity count, task count,
                    search parameters, and verification requirements.
            output_file: Optional path to JSON file for incremental saving. If provided,
                        each verified question will be immediately appended to the file.

        Returns:
            List of dictionaries containing question-answer pairs with metadata:
            - question: The generated question
            - answer: The ground-truth answer
            - entity: Entity name
            - domain: Entity domain
            - description: Entity description
            - search_context: Search results used for question construction
            - candidates: List of candidate answers generated by different agents
            - verification_results: List of verification results for each candidate
        """
        if any([request.embedding_path, request.faiss_index_path, request.text_mapping_path]) and not all(
            [request.embedding_path, request.faiss_index_path, request.text_mapping_path]
        ):
            logger.info(
                "If any of embedding_path, faiss_index_path, and text_mapping_path is specified, all must be specified."
            )
            exit(1)
        if not request.domain:
            logger.warning("No domains specified, using domains by generation")
            request.domain = self._get_domains(request.num_domains)

        logger.info(
            f"Starting generation for domains: {request.domain}, "
            f"entities per domain: {request.num_entities_each_domain}"
        )

        # Optional: Load embedding model and faiss index
        idx = 0  # Initialize idx for all cases
        if request.embedding_path:
            self.embedding = SentenceTransformer(request.embedding_path)
            if exists(request.faiss_index_path):
                self.faiss_index = faiss.read_index(request.faiss_index_path)
            else:
                dim = self.embedding.get_sentence_embedding_dimension()
                self.faiss_index = faiss.IndexFlatL2(dim)
            if exists(request.text_mapping_path):
                with open(request.text_mapping_path, "r") as f:
                    self.text_mapping = json.load(f)
                idx = len(self.text_mapping)

            # Initialize locks for thread-safe operations
            self._file_lock = threading.Lock()
            self._index_lock = threading.Lock()

        # Get tool call map wrapped with request constraints
        tool_call_map = self._get_tool_call_map_for_request(request)

        # Get max_workers from request, default to 4
        max_workers = getattr(request, "max_workers", 4)
        if max_workers <= 0:
            max_workers = 4

        # Step 1: Entity Sampling
        entities = self._sample_entities(
            llm=self.llm,
            num_entities_each_domain=request.num_entities_each_domain,
            domains=request.domain,
            num_iterations=request.num_iterations,
            entities_per_entity=request.search_breadth,
            max_workers=5,  # indicates the number of threads to use for parallel processing
        )
        logger.info(f"Sampled {len(entities)} entities")

        # Initialize locks if not already initialized (for cases without embedding)
        if self._file_lock is None:
            self._file_lock = threading.Lock()
        if self._index_lock is None:
            self._index_lock = threading.Lock()

        # Step 2 & 3: Parallel processing of entities and questions
        results: List[Dict[str, Any]] = []
        idx_counter = (
            [idx] if request.embedding_path else [0]
        )  # Use list to allow modification in nested functions

        def process_entity(entity: Entity) -> List[Dict[str, Any]]:
            """Process a single entity: construct questions and generate answers."""
            entity_results = []
            try:
                logger.info(f"Constructing questions for entity: {entity.name}")
                task_list = self._construct_question(
                    llm=self.llm,
                    tools=self._get_tools_info(),
                    tool_call_map=tool_call_map,
                    entity=entity,
                    num_tasks=request.num_tasks_each_entity,
                )
                logger.info(f"Generated {len(task_list)} questions for {entity.name}")

                # Process questions in parallel
                def process_qa_pair(qa_pair) -> Optional[Dict[str, Any]]:
                    """Process a single question-answer pair."""
                    try:
                        logger.info(f"Generating answers for question: {qa_pair.question[:50]}...")
                        candidates = self._generate_answers(
                            llm=self.llm,
                            tools=self._get_tools_info(),
                            tool_call_map=tool_call_map,
                            qa_pair=qa_pair,
                        )
                        logger.info(f"Generated {len(candidates)} candidate answers")

                        should_retain, verification_results = self._verify_candidates(
                            llm=self.llm,
                            qa_pair=qa_pair,
                            candidates=candidates,
                            require_all_incorrect=request.require_all_incorrect,
                        )

                        if should_retain:
                            result_item = {
                                "environment": {
                                    "category": qa_pair.entity.domain,
                                    "records": {
                                        "search_context": qa_pair.search_context,
                                        "construct_context": qa_pair.all_search_context,
                                        "answer_context": [
                                            candidate.all_search_context for candidate in candidates
                                        ],
                                    },
                                    "record_count": len(qa_pair.all_search_context)
                                    + sum([len(candidate.all_search_context) for candidate in candidates]),
                                },
                                "tools": ["search", "visit"],
                                "tasks": {
                                    "task_id": str(uuid.uuid5(uuid.NAMESPACE_DNS, qa_pair.question)),
                                    "question": qa_pair.question,
                                    "answer": qa_pair.answer,
                                    "entity": qa_pair.entity.name,
                                },
                            }
                            logger.info(f"Retained QA pair for entity: {entity.name}")

                            # Thread-safe file writing
                            if output_file:
                                with self._file_lock:
                                    self._append_to_json_file(output_file, result_item)

                            all_search_context = qa_pair.all_search_context
                            for candidate in candidates:
                                all_search_context.extend(candidate.all_search_context)
                            # Remove all empty string entries from all_search_context
                            all_search_context = [c for c in all_search_context if len(c) > 20]
                            # Thread-safe embedding and index update
                            if self.embedding and self.faiss_index:
                                all_context = []
                                chunk_to_original = {}  # Map chunks to original text
                                for text in all_search_context:
                                    chunks = self._chunk_context(text)
                                    all_context.extend(chunks)
                                    for chunk in chunks:
                                        chunk_to_original[chunk] = text

                                # Generate embeddings
                                with torch.no_grad():
                                    search_embeddings = self.embedding.encode(all_context)
                                    if len(search_embeddings.shape) == 1:
                                        search_embeddings = search_embeddings.reshape(1, -1)

                                # Thread-safe index and mapping update
                                with self._index_lock:
                                    current_idx = idx_counter[0]
                                    for chunk in all_context:
                                        self.text_mapping[current_idx] = {
                                            "chunk_text": chunk,
                                            "original_text": chunk_to_original.get(chunk, ""),
                                        }
                                        current_idx += 1
                                    idx_counter[0] = current_idx

                                    self.faiss_index.add(search_embeddings)
                                    torch.cuda.empty_cache()

                                    # Save index and mapping periodically (every 10 items)
                                    if current_idx % 10 == 0:
                                        faiss.write_index(self.faiss_index, request.faiss_index_path)
                                        with open(request.text_mapping_path, "w") as f:
                                            json.dump(self.text_mapping, f, indent=2, ensure_ascii=False)

                            return result_item
                        return None
                    except Exception as e:
                        logger.error(f"Error processing QA pair: {e}", exc_info=True)
                        return None

                # Process questions in parallel
                with ThreadPoolExecutor(max_workers=max_workers) as executor:
                    future_to_qa = {
                        executor.submit(process_qa_pair, qa_pair): qa_pair for qa_pair in task_list
                    }
                    for future in as_completed(future_to_qa):
                        result = future.result()
                        if result:
                            entity_results.append(result)

            except Exception as e:
                logger.error(f"Error processing entity {entity.name}: {e}", exc_info=True)

            return entity_results

        # Process entities in parallel
        logger.info(f"Starting parallel processing with {max_workers} workers")
        with ThreadPoolExecutor(max_workers=max_workers) as executor:
            future_to_entity = {executor.submit(process_entity, entity): entity for entity in entities}
            for future in as_completed(future_to_entity):
                entity_results = future.result()
                results.extend(entity_results)

        # Final save of index and mapping if embedding is used
        if self.embedding and self.faiss_index and request.faiss_index_path:
            with self._index_lock:
                faiss.write_index(self.faiss_index, request.faiss_index_path)
                with open(request.text_mapping_path, "w") as f:
                    json.dump(self.text_mapping, f, indent=2, ensure_ascii=False)

        logger.info(f"Generated {len(results)} verified question-answer pairs")
        return results

    def _get_tools_info(self) -> List[Dict[str, Any]]:
        """Get the tools information for the agent.

        Returns:
            List of tool specifications in OpenAI function calling format.
        """
        return [
            {
                "type": "function",
                "function": {
                    "name": "search",
                    "description": "Search the web for information",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "query": {
                                "type": "string",
                                "description": "The search query",
                            },
                            "max_results": {
                                "type": "integer",
                                "description": "The maximum number of results to return",
                            },
                            "depth": {
                                "type": "integer",
                                "description": "Use depth=2, 3, 4+ to get more obscure, less common results that appear deeper in search results. When you need to find obscure facts, metadata, or technical details, try deeper depth (2-10).",
                            },
                        },
                        "required": ["query", "max_results", "depth"],
                    },
                },
            },
            {
                "type": "function",
                "function": {
                    "name": "visit",
                    "description": "Visit a website and extract relevant content",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "url": {
                                "type": "string",
                                "description": "The URL to visit",
                            },
                            "goal": {
                                "type": "string",
                                "description": "The goal of the visit",
                            },
                        },
                        "required": ["url", "goal"],
                    },
                },
            },
        ]

    def _get_tool_call_map(self) -> Dict[str, Callable]:
        """Get the tool call map for the agent.

        Returns:
            Dictionary mapping tool names to their execution functions.
        """
        return {
            "search": self.search_tool.execute,
            "visit": self.visit_tool.execute,
        }

    def _get_tool_call_map_for_request(self, request: GenerationRequest) -> Dict[str, Callable]:
        """Get the tool call map for the agent, wrapped to respect request constraints.

        Args:
            request: The generation request containing search constraints.

        Returns:
            Dictionary mapping tool names to their wrapped execution functions.
        """

        def wrapped_search(query: str, max_results: int = 5, depth: int = 1) -> List[Dict[str, str]]:
            # Clamp depth and max_results to request constraints
            clamped_depth = min(max(1, depth), request.search_depth)
            clamped_breadth = min(max(1, max_results), request.search_breadth)
            return self.search_tool.execute(query, max_results=clamped_breadth, depth=clamped_depth)

        return {
            "search": wrapped_search,
            "visit": self.visit_tool.execute,
        }

    def _get_domains(self, num_domains: int) -> List[str]:
        """Get the domains for the agent.

        Returns:
            List of domain names.
        """
        messages = [
            {
                "role": "user",
                "content": self.DOMAIN_SAMPLER_PROMPT.format(num_domains=1),
            }
        ]
        domains = []
        while len(domains) < num_domains:
            try:
                response = self.llm.chat_completion(messages=messages, temperature=1.0, top_p=0.95)
                domain = json.loads(response)[0]
                if domain not in domains:
                    domains.append(domain)
            except Exception as e:
                continue
        return domains

    def _append_to_json_file(self, file_path: str, new_item: Dict[str, Any]) -> None:
        """Append a new item to a JSON array file.

        Args:
            file_path: Path to the JSON file
            new_item: New item to append to the array
        """
        file_path_obj = Path(file_path)

        # Ensure the directory exists
        file_path_obj.parent.mkdir(parents=True, exist_ok=True)

        if file_path_obj.exists():
            try:
                with open(file_path, "r", encoding="utf-8") as f:
                    existing_data = json.load(f)
                    if not isinstance(existing_data, list):
                        existing_data = []
            except (json.JSONDecodeError, IOError):
                existing_data = []
        else:
            existing_data = []

        existing_data.append(new_item)

        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(existing_data, f, indent=2, ensure_ascii=False)

        logger.info(f"Appended result to {file_path}")

    def _chunk_context(self, context: str) -> List[str]:
        """Chunk the context into smaller chunks.

        Args:
            context: The context to chunk

        Returns:
            List of chunks
        """
        chunks = []
        chunk_size = 1024
        overlap = 128

        import re

        def _remove_urls(text: str) -> str:
            url_pattern = r"https?://[^\s]+"
            return re.sub(url_pattern, "", text)

        context = _remove_urls(context)
        context = ftfy.fix_text(context)

        for i in range(0, len(context), chunk_size - overlap):
            chunks.append(context[i : i + chunk_size])
        return chunks
