from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass
from typing import Any, Callable, Dict, List, Optional

from agent_gem.llm import LLMClient

from .prompt_mixin import PromptMixin
from .question_constructor import QuestionAnswerPair

logger = logging.getLogger(__name__)


@dataclass
class AgentConfig:
    """Configuration for an answer generation agent.

    Attributes:
        checkpoint: Optional model checkpoint identifier
        system_prompt: System prompt for the agent
        temperature: Sampling temperature for generation
        max_tokens: Maximum tokens to generate
        name: Configuration name identifier
    """

    checkpoint: Optional[str] = None
    system_prompt: str = (
        "You are a helpful assistant that answers questions using external web search "
        "results. First think step-by-step about what to search, then synthesize a "
        "final answer based only on reliable evidence."
    )
    temperature: float = 0.7
    max_tokens: int = 1024
    name: str = "default"


@dataclass
class CandidateAnswer:
    """Represents a candidate answer generated by an answer generation agent.

    Attributes:
        answer: The generated answer text
        generator_config: The agent configuration used to generate this answer
    """

    answer: str
    generator_config: AgentConfig
    all_search_context: List[str]


class AnswerGeneratorMixin(PromptMixin):
    """Answer-generation agent that uses a ReAct-style loop with the search tool.

    This mixin provides functionality to generate diverse candidate answers
    using multiple agent configurations with different personalities and parameters.
    """

    def _default_agent_configs(self) -> List[AgentConfig]:
        """Generate default heterogeneous agent configurations.

        Returns:
            List of AgentConfig objects with varying personalities:
            - conservative: Low temperature, precision-focused
            - balanced: Medium temperature, balanced approach
            - creative: High temperature, detailed and engaging
        """
        return [
            AgentConfig(
                name="conservative",
                system_prompt=(
                    "You are a careful assistant that verifies facts with web search before answering. Prefer precision over coverage. When answering questions:\n"
                    "1. Use the available search tool to find relevant and reliable information.\n"
                    "2. Synthesize information from multiple sources when needed.\n"
                    "3. Provide an accurate answer based on your search results, and put your final answer in \\boxed{} format.\n"
                    "4. You are asked to perform search only once to find the answer in each turn. Each time you search, think about what information you need to find next turn based on what you have already found.\n"
                    "5. As much as possible, use the search tool instead of relying on your own knowledge.\n"
                    "\n"
                    "For example:\n"
                    '- If the answer is "American", write: \\boxed{American}\n'
                    '- If the answer is "yes", write: \\boxed{yes}\n'
                    '- If the answer is a year like "1985", write: \\boxed{1985}\n'
                    "\n"
                    "Remember to search thoroughly and provide your final answer clearly within the \\boxed{} format."
                ),
                temperature=0.3,
                max_tokens=1024,
            ),
            AgentConfig(
                name="balanced",
                system_prompt=(
                    "You are a balanced assistant that combines careful fact-checking with comprehensive coverage. When answering questions:\n"
                    "1. Use the available search tool to gather information from multiple perspectives and sources.\n"
                    "2. Balance accuracy with breadth - don't sacrifice precision for completeness.\n"
                    "3. Provide well-rounded answers that consider different viewpoints, and put your final answer in \\boxed{} format.\n"
                    "4. You can perform multiple searches if needed to build a complete picture, but prioritize efficient information gathering.\n"
                    "5. Use search results as your primary knowledge source while maintaining objectivity.\n"
                    "\n"
                    "For example:\n"
                    "- If exploring a topic with multiple aspects, provide balanced coverage: \\boxed{comprehensive answer}\n"
                    "- When there are competing theories, present evidence for each: \\boxed{balanced analysis}\n"
                    "- For complex questions, synthesize diverse information: \\boxed{well-rounded conclusion}\n"
                    "\n"
                    "Remember to search strategically and provide balanced, comprehensive answers within the \\boxed{} format."
                ),
                temperature=0.7,
                max_tokens=1024,
            ),
            AgentConfig(
                name="creative",
                system_prompt=(
                    "You are an innovative assistant that leverages web search to fuel creative thinking and generate engaging narratives. When answering questions:\n"
                    "1. Use the available search tool to discover unique insights, historical context, and inspiring examples.\n"
                    "2. Transform factual information into compelling, well-structured responses that captivate the reader.\n"
                    "3. Provide creative answers that go beyond basic facts, weaving information into engaging stories, and put your final answer in \\boxed{} format.\n"
                    "4. Feel free to make multiple targeted searches to uncover the most interesting angles and connections.\n"
                    "5. Use search results as inspiration while adding your own creative interpretation and analysis.\n"
                    "\n"
                    "For example:\n"
                    "- Transform dry facts into engaging narratives: \\boxed{creative storytelling}\n"
                    "- Connect seemingly unrelated concepts: \\boxed{innovative connections}\n"
                    "- Present information in novel, memorable ways: \\boxed{engaging presentation}\n"
                    "\n"
                    "Remember to search creatively and craft your answers into compelling, innovative responses within the \\boxed{} format."
                ),
                temperature=0.9,
                max_tokens=1024,
            ),
        ]

    def _generate_answers(
        self,
        llm: LLMClient,
        tools: List[Dict[str, Any]],
        tool_call_map: Dict[str, Callable],
        qa_pair: QuestionAnswerPair,
        agent_configs: Optional[List[AgentConfig]] = None,
    ) -> List[CandidateAnswer]:
        """Generate diverse candidate answers for a question using multiple agent configurations.

        Args:
            llm: LLM client for generating answers
            tools: List of tool specifications
            tool_call_map: Mapping of tool names to execution functions
            qa_pair: Question-answer pair to generate answers for
            agent_configs: Optional list of agent configurations to use.
                         If None, uses default configurations.

        Returns:
            List of candidate answers generated by different agent configurations
        """
        candidates: List[CandidateAnswer] = []
        configs = self._default_agent_configs() if agent_configs is None else agent_configs

        for config in configs:
            logger.info(f"Generating answer with config: {config.name}")
            candidate = self._generate_with_config(llm, tools, tool_call_map, qa_pair, config)
            if candidate:
                candidates.append(candidate)
            else:
                logger.warning(f"Failed to generate answer with config: {config.name}")

        return candidates

    def _generate_with_config(
        self,
        llm: LLMClient,
        tools: List[Dict[str, Any]],
        tool_call_map: Dict[str, Callable],
        qa_pair: QuestionAnswerPair,
        config: AgentConfig,
    ) -> Optional[CandidateAnswer]:
        """Generate an answer using a specific configuration with search-tool ReAct.

        Args:
            llm: LLM client for generating answers
            tools: List of tool specifications
            tool_call_map: Mapping of tool names to execution functions
            qa_pair: Question-answer pair to generate answer for
            config: Agent configuration to use

        Returns:
            CandidateAnswer if generation succeeds, None otherwise
        """
        try:
            messages = [
                {"role": "system", "content": config.system_prompt},
                {"role": "user", "content": qa_pair.question},
            ]

            # Use chat completion with agent tools
            answer, search_context = llm.chat_with_agent(
                messages=messages,
                tools=tools,
                tool_call_map=tool_call_map,
                temperature=config.temperature,
                max_tokens=config.max_tokens,
            )

            # Try to extract answer from boxed format or JSON in the model output
            try:
                answer_text = answer.strip()

                # First try to extract from \boxed{} format (highest priority)
                boxed_match = re.search(r"\\boxed\{([^}]+)\}", answer_text)
                if boxed_match:
                    answer = boxed_match.group(1).strip()
                else:
                    # If no boxed format found, return None
                    logger.debug("No \\boxed{} format found in answer")
                    answer = None

            except Exception as e:
                # If parsing fails, return None
                logger.debug(f"Failed to extract boxed answer: {e}")
                answer = None

            if not answer:
                logger.warning(f"Empty answer generated for config: {config.name}")
            return CandidateAnswer(
                answer=answer,
                generator_config=config,
                all_search_context=search_context,
            )
        except Exception as e:
            logger.error(f"Error generating answer with config {config.name}: {e}")
            return None
