from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass
from typing import Any, Callable, Dict, List, Optional

from agent_gem.llm import LLMClient

from .prompt_mixin import PromptMixin
from .question_constructor import QuestionAnswerPair

logger = logging.getLogger(__name__)


@dataclass
class AgentConfig:
    """Configuration for an answer generation agent.

    Attributes:
        checkpoint: Optional model checkpoint identifier
        system_prompt: System prompt for the agent
        temperature: Sampling temperature for generation
        max_tokens: Maximum tokens to generate
        name: Configuration name identifier
    """

    checkpoint: Optional[str] = None
    system_prompt: str = (
        "You are a helpful assistant that answers questions using external web search "
        "results. First think step-by-step about what to search, then synthesize a "
        "final answer based only on reliable evidence."
    )
    temperature: float = 0.7
    max_tokens: int = 1024
    name: str = "default"


@dataclass
class CandidateAnswer:
    """Represents a candidate answer generated by an answer generation agent.

    Attributes:
        answer: The generated answer text
        generator_config: The agent configuration used to generate this answer
    """

    answer: str
    generator_config: AgentConfig


class AnswerGeneratorMixin(PromptMixin):
    """Answer-generation agent that uses a ReAct-style loop with the search tool.

    This mixin provides functionality to generate diverse candidate answers
    using multiple agent configurations with different personalities and parameters.
    """

    def _default_agent_configs(self) -> List[AgentConfig]:
        """Generate default heterogeneous agent configurations.

        Returns:
            List of AgentConfig objects with varying personalities:
            - conservative: Low temperature, precision-focused
            - balanced: Medium temperature, balanced approach
            - creative: High temperature, detailed and engaging
        """
        return [
            AgentConfig(
                name="conservative",
                system_prompt=(
                    "You are a careful assistant that verifies facts with web search "
                    "before answering. Prefer precision over coverage."
                ),
                temperature=0.3,
                max_tokens=1024,
            ),
            AgentConfig(
                name="balanced",
                system_prompt=(
                    "You are a helpful assistant that uses web search results to provide "
                    "accurate and comprehensive answers."
                ),
                temperature=0.7,
                max_tokens=1024,
            ),
            AgentConfig(
                name="creative",
                system_prompt=(
                    "You are a creative assistant that uses web search to gather rich "
                    "context and then writes detailed and engaging answers."
                ),
                temperature=0.9,
                max_tokens=1024,
            ),
        ]

    def _generate_answers(
        self,
        llm: LLMClient,
        tools: List[Dict[str, Any]],
        tool_call_map: Dict[str, Callable],
        qa_pair: QuestionAnswerPair,
        agent_configs: Optional[List[AgentConfig]] = None,
    ) -> List[CandidateAnswer]:
        """Generate diverse candidate answers for a question using multiple agent configurations.

        Args:
            llm: LLM client for generating answers
            tools: List of tool specifications
            tool_call_map: Mapping of tool names to execution functions
            qa_pair: Question-answer pair to generate answers for
            agent_configs: Optional list of agent configurations to use.
                         If None, uses default configurations.

        Returns:
            List of candidate answers generated by different agent configurations
        """
        candidates: List[CandidateAnswer] = []
        configs = self._default_agent_configs() if agent_configs is None else agent_configs

        for config in configs:
            logger.debug(f"Generating answer with config: {config.name}")
            candidate = self._generate_with_config(llm, tools, tool_call_map, qa_pair, config)
            if candidate:
                candidates.append(candidate)
            else:
                logger.warning(f"Failed to generate answer with config: {config.name}")

        return candidates

    def _generate_with_config(
        self,
        llm: LLMClient,
        tools: List[Dict[str, Any]],
        tool_call_map: Dict[str, Callable],
        qa_pair: QuestionAnswerPair,
        config: AgentConfig,
    ) -> Optional[CandidateAnswer]:
        """Generate an answer using a specific configuration with search-tool ReAct.

        Args:
            llm: LLM client for generating answers
            tools: List of tool specifications
            tool_call_map: Mapping of tool names to execution functions
            qa_pair: Question-answer pair to generate answer for
            config: Agent configuration to use

        Returns:
            CandidateAnswer if generation succeeds, None otherwise
        """
        try:
            messages = [
                {"role": "system", "content": config.system_prompt},
                {
                    "role": "user",
                    "content": (
                        f"Question: {qa_pair.question}\n\n"
                        "Please provide a comprehensive answer to the question, "
                        'and output the answer in the following format: {"answer": "[answer]"}'
                    ),
                },
            ]

            # Use chat completion with agent tools
            answer, search_context = llm.chat_with_agent(
                messages=messages,
                tools=tools,
                tool_call_map=tool_call_map,
                temperature=config.temperature,
                max_tokens=config.max_tokens,
            )

            # Try to extract answer from JSON object in the model output
            try:
                answer_json = answer.strip()
                # Handle markdown code blocks
                if answer_json.startswith("```"):
                    match = re.search(r"```(?:json)?\s*(.*?)\s*```", answer_json, re.DOTALL)
                    if match:
                        answer_json = match.group(1)

                answer_obj = json.loads(answer_json)
                answer = answer_obj.get("answer", "").strip()
            except (json.JSONDecodeError, KeyError, AttributeError) as e:
                # Fallback: use the answer as-is if JSON parsing fails
                logger.debug(f"Failed to parse JSON from answer, using raw answer: {e}")

            if not answer:
                logger.warning(f"Empty answer generated for config: {config.name}")
                return None

            return CandidateAnswer(
                answer=answer,
                generator_config=config,
            )
        except Exception as e:
            logger.error(f"Error generating answer with config {config.name}: {e}")
            return None

    def _direct_answer(
        self,
        llm: LLMClient,
        qa_pair: QuestionAnswerPair,
        config: AgentConfig,
    ) -> Optional[CandidateAnswer]:
        """Fallback strategy: answer directly without using search tools.

        Args:
            llm: LLM client for generating answers
            qa_pair: Question-answer pair to generate answer for
            config: Agent configuration to use

        Returns:
            CandidateAnswer if generation succeeds, None otherwise
        """
        messages = [
            {"role": "system", "content": config.system_prompt},
            {
                "role": "user",
                "content": (
                    f"Question: {qa_pair.question}\n\n"
                    "Please provide a comprehensive answer to the question."
                ),
            },
        ]
        try:
            answer = llm.chat_completion(
                messages=messages,
                temperature=config.temperature,
                max_tokens=config.max_tokens,
            )
            return CandidateAnswer(answer=answer, generator_config=config)
        except Exception as e:
            logger.warning(f"Error in direct answer fallback for config {config.name}: {e}")
            return None
